#!/usr/bin/env python3
"""JANUS P0 preservation integration evidence verifier.

This tool evaluates *already produced* local evidence against the pre-registered
P0 preservation conditions. It does not materialize repositories, replay source
code, execute commands, mutate Git, or generate producer receipts.

The input evidence bundle may contain sensitive local digests. The emitted
summary is deliberately redacted and never includes those local digests, failed
variant IDs, conflict message IDs, checkpoint IDs, or source pins.

Evidence consistency is not empirical replay. Producer receipts still need to
be generated by their own exact-head harnesses.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any

BUNDLE_SCHEMA = "janus.nexus.preservation_integration_evidence.v1"
LOCK_SCHEMA = "janus.nexus.preservation_integration_lock.v1"
SUMMARY_SCHEMA = "janus.nexus.preservation_integration_public_summary.v1"
PREREGISTRATION_RECEIPT = "5308388940"
EXPECTED_SOURCE_COUNT = 44
HEX40 = re.compile(r"^[0-9a-f]{40}$")
HEX64 = re.compile(r"^[0-9a-f]{64}$")

PRODUCER_KEYS = {
    "materializer",
    "privacy_projection",
    "variant_lineage",
    "handoff_ledger",
    "swarm_recovery",
}

BUNDLE_KEYS = {
    "schema",
    "producer_heads",
    "materializer",
    "lineage",
    "handoff",
    "swarm",
    "source_guard",
}

LOCK_KEYS = {
    "schema",
    "preregistration_receipt",
    "expected_source_count",
    "privacy_mode",
    "producer_heads",
}


class PreservationEvidenceError(RuntimeError):
    """Fail-closed evidence admission error."""


def canonical_bytes(value: Any) -> bytes:
    return json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    ).encode("utf-8")


def digest(value: Any) -> str:
    return hashlib.sha256(canonical_bytes(value)).hexdigest()


def _require_exact_keys(value: Any, expected: set[str], field: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise PreservationEvidenceError(f"{field} must be an object")
    keys = set(value)
    if keys != expected:
        missing = sorted(expected - keys)
        extra = sorted(keys - expected)
        raise PreservationEvidenceError(
            f"{field} keys mismatch; missing={missing}; extra={extra}"
        )
    return value


def _require_sha(value: Any, field: str) -> str:
    if not isinstance(value, str) or not HEX40.fullmatch(value):
        raise PreservationEvidenceError(f"{field} must be exact lowercase 40-hex Git SHA")
    return value


def _require_digest(value: Any, field: str) -> str:
    if not isinstance(value, str) or not HEX64.fullmatch(value):
        raise PreservationEvidenceError(f"{field} must be lowercase 64-hex digest")
    return value


def _require_bool(value: Any, field: str, expected: bool | None = None) -> bool:
    if type(value) is not bool:
        raise PreservationEvidenceError(f"{field} must be boolean")
    if expected is not None and value is not expected:
        raise PreservationEvidenceError(f"{field} must be {expected}")
    return value


def validate_producer_heads(raw: Any, field: str) -> dict[str, str]:
    value = _require_exact_keys(raw, PRODUCER_KEYS, field)
    return {key: _require_sha(value[key], f"{field}.{key}") for key in sorted(PRODUCER_KEYS)}


def validate_lock(raw: Any) -> dict[str, Any]:
    value = _require_exact_keys(raw, LOCK_KEYS, "lock")
    if value.get("schema") != LOCK_SCHEMA:
        raise PreservationEvidenceError("lock schema mismatch")
    if value.get("preregistration_receipt") != PREREGISTRATION_RECEIPT:
        raise PreservationEvidenceError("lock preregistration receipt mismatch")
    if value.get("expected_source_count") != EXPECTED_SOURCE_COUNT:
        raise PreservationEvidenceError("lock expected source count mismatch")
    if value.get("privacy_mode") != "LOCAL_EVIDENCE_PUBLIC_REDACTED_SUMMARY":
        raise PreservationEvidenceError("lock privacy mode mismatch")
    heads = validate_producer_heads(value.get("producer_heads"), "lock.producer_heads")
    return {
        "schema": LOCK_SCHEMA,
        "preregistration_receipt": PREREGISTRATION_RECEIPT,
        "expected_source_count": EXPECTED_SOURCE_COUNT,
        "privacy_mode": "LOCAL_EVIDENCE_PUBLIC_REDACTED_SUMMARY",
        "producer_heads": heads,
    }


def validate_bundle(raw: Any) -> dict[str, Any]:
    value = _require_exact_keys(raw, BUNDLE_KEYS, "bundle")
    if value.get("schema") != BUNDLE_SCHEMA:
        raise PreservationEvidenceError("bundle schema mismatch")
    heads = validate_producer_heads(value.get("producer_heads"), "bundle.producer_heads")

    materializer = _require_exact_keys(
        value.get("materializer"),
        {
            "source_count",
            "clean_target_rebuild_exercised",
            "rebuild_a_digest",
            "rebuild_b_digest",
            "local_exact_replay_passed",
            "privacy_projection_passed",
            "source_pin_drift",
            "source_writeback_observed",
            "destructive_cleanup_required_for_pass",
        },
        "bundle.materializer",
    )
    if materializer.get("source_count") != EXPECTED_SOURCE_COUNT:
        raise PreservationEvidenceError("materializer source_count must be 44")
    _require_bool(materializer.get("clean_target_rebuild_exercised"), "materializer.clean_target_rebuild_exercised", True)
    rebuild_a = _require_digest(materializer.get("rebuild_a_digest"), "materializer.rebuild_a_digest")
    rebuild_b = _require_digest(materializer.get("rebuild_b_digest"), "materializer.rebuild_b_digest")
    if rebuild_a != rebuild_b:
        raise PreservationEvidenceError("independent materializer rebuild digests differ")
    _require_bool(materializer.get("local_exact_replay_passed"), "materializer.local_exact_replay_passed", True)
    _require_bool(materializer.get("privacy_projection_passed"), "materializer.privacy_projection_passed", True)
    _require_bool(materializer.get("source_pin_drift"), "materializer.source_pin_drift", False)
    _require_bool(materializer.get("source_writeback_observed"), "materializer.source_writeback_observed", False)
    _require_bool(
        materializer.get("destructive_cleanup_required_for_pass"),
        "materializer.destructive_cleanup_required_for_pass",
        False,
    )

    lineage = _require_exact_keys(
        value.get("lineage"),
        {
            "expected_head_digest",
            "observed_head_digest",
            "failed_variant_ids",
            "failed_variants_retained",
        },
        "bundle.lineage",
    )
    expected_lineage = _require_digest(lineage.get("expected_head_digest"), "lineage.expected_head_digest")
    observed_lineage = _require_digest(lineage.get("observed_head_digest"), "lineage.observed_head_digest")
    if expected_lineage != observed_lineage:
        raise PreservationEvidenceError("lineage expected/observed head digest mismatch")
    failed_ids = lineage.get("failed_variant_ids")
    if not isinstance(failed_ids, list) or not failed_ids:
        raise PreservationEvidenceError("lineage requires at least one retained failed variant")
    if len(failed_ids) != len(set(failed_ids)):
        raise PreservationEvidenceError("lineage failed_variant_ids must be unique")
    for index, item in enumerate(failed_ids):
        _require_digest(item, f"lineage.failed_variant_ids[{index}]")
    _require_bool(lineage.get("failed_variants_retained"), "lineage.failed_variants_retained", True)

    handoff = _require_exact_keys(
        value.get("handoff"),
        {
            "expected_head_digest",
            "observed_head_digest",
            "conflict_message_ids",
            "conflicts_retained",
            "reconciliation_status",
            "majority_vote_used",
        },
        "bundle.handoff",
    )
    expected_handoff = _require_digest(handoff.get("expected_head_digest"), "handoff.expected_head_digest")
    observed_handoff = _require_digest(handoff.get("observed_head_digest"), "handoff.observed_head_digest")
    if expected_handoff != observed_handoff:
        raise PreservationEvidenceError("handoff expected/observed head digest mismatch")
    conflict_ids = handoff.get("conflict_message_ids")
    if (
        not isinstance(conflict_ids, list)
        or len(conflict_ids) < 2
        or len(conflict_ids) != len(set(conflict_ids))
        or not all(isinstance(item, str) and item.strip() for item in conflict_ids)
    ):
        raise PreservationEvidenceError("handoff requires at least two unique conflict message IDs")
    _require_bool(handoff.get("conflicts_retained"), "handoff.conflicts_retained", True)
    if handoff.get("reconciliation_status") != "HOLD_RECONCILE":
        raise PreservationEvidenceError("handoff reconciliation must be HOLD_RECONCILE")
    _require_bool(handoff.get("majority_vote_used"), "handoff.majority_vote_used", False)

    swarm = _require_exact_keys(
        value.get("swarm"),
        {
            "checkpoint_digest",
            "receipt_digest",
            "session_drop_exercised",
            "resume_decision",
            "source_pin_drift",
            "duplicate_source_mutation_observed",
        },
        "bundle.swarm",
    )
    _require_digest(swarm.get("checkpoint_digest"), "swarm.checkpoint_digest")
    _require_digest(swarm.get("receipt_digest"), "swarm.receipt_digest")
    _require_bool(swarm.get("session_drop_exercised"), "swarm.session_drop_exercised", True)
    if swarm.get("resume_decision") != "RESUME":
        raise PreservationEvidenceError("swarm resume_decision must be RESUME")
    _require_bool(swarm.get("source_pin_drift"), "swarm.source_pin_drift", False)
    _require_bool(
        swarm.get("duplicate_source_mutation_observed"),
        "swarm.duplicate_source_mutation_observed",
        False,
    )

    source_guard = _require_exact_keys(
        value.get("source_guard"),
        {
            "before_identity_digest",
            "after_identity_digest",
            "writeback_observed",
            "destructive_effect_observed",
        },
        "bundle.source_guard",
    )
    before = _require_digest(source_guard.get("before_identity_digest"), "source_guard.before_identity_digest")
    after = _require_digest(source_guard.get("after_identity_digest"), "source_guard.after_identity_digest")
    if before != after:
        raise PreservationEvidenceError("source identity changed across replay")
    _require_bool(source_guard.get("writeback_observed"), "source_guard.writeback_observed", False)
    _require_bool(
        source_guard.get("destructive_effect_observed"),
        "source_guard.destructive_effect_observed",
        False,
    )

    # Canonical JSON round trip rejects non-JSON values and detaches callers.
    try:
        cleaned = json.loads(canonical_bytes(value).decode("utf-8"))
    except (TypeError, ValueError) as exc:
        raise PreservationEvidenceError(f"bundle is not canonical JSON data: {exc}") from exc
    cleaned["producer_heads"] = heads
    return cleaned


def evaluate(bundle_raw: Any, lock_raw: Any) -> dict[str, Any]:
    lock = validate_lock(lock_raw)
    bundle = validate_bundle(bundle_raw)
    if bundle["producer_heads"] != lock["producer_heads"]:
        raise PreservationEvidenceError("bundle producer heads do not match external lock")

    summary = {
        "schema": SUMMARY_SCHEMA,
        "decision": "EVIDENCE_BUNDLE_CONSISTENT",
        "preregistration_receipt": PREREGISTRATION_RECEIPT,
        "producer_heads": lock["producer_heads"],
        "producer_lock_digest": digest(lock),
        "source_count": EXPECTED_SOURCE_COUNT,
        "clean_target_rebuild_exercised": True,
        "independent_rebuild_identity_reproduced": True,
        "local_exact_replay_passed": True,
        "privacy_projection_passed": True,
        "lineage_expected_head_reproduced": True,
        "failed_variant_retention": True,
        "handoff_expected_head_reproduced": True,
        "conflict_retention_and_hold_reconcile": True,
        "swarm_session_drop_recovery": True,
        "source_pin_drift": False,
        "source_writeback_observed": False,
        "destructive_effect_observed": False,
        "majority_vote_used": False,
        "local_sensitive_evidence_persisted_in_summary": False,
        "empirical_replay_claimed_by_this_verifier": False,
        "merge_permission_granted": False,
        "authority_delta": 0,
        "mass_effect_budget_delta": 0,
        "claim_ceiling": (
            "This summary proves only that a supplied local evidence bundle is internally "
            "consistent with an external producer-head lock and the pre-registered P0 conditions. "
            "It does not prove that producer harnesses honestly generated the evidence, perform "
            "repository acquisition, establish an empirical owner-wide replay, or grant merge/writeback authority."
        ),
    }
    summary["public_summary_digest"] = digest(summary)
    return summary


def _load_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise PreservationEvidenceError(f"cannot load JSON input: {path}: {exc}") from exc


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bundle", required=True, type=Path)
    parser.add_argument("--lock", required=True, type=Path)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        result = evaluate(_load_json(args.bundle), _load_json(args.lock))
    except PreservationEvidenceError as exc:
        failure = {
            "ok": False,
            "schema": SUMMARY_SCHEMA,
            "error": str(exc),
            "empirical_replay_claimed_by_this_verifier": False,
            "merge_permission_granted": False,
            "authority_delta": 0,
            "mass_effect_budget_delta": 0,
        }
        print(json.dumps(failure, ensure_ascii=False, sort_keys=True), file=sys.stderr)
        return 2
    print(json.dumps(result, ensure_ascii=False, sort_keys=True, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
